version: 2.1
jobs:
  build_db:
    docker:
      - image: postgres:latest
        environment:
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=test
          - PGPORT=54320
          - PGHOST=localhost
          - PGDATABASE=test
  build_test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            python setup.py sdist bdist_wheel
            python -m pip install pytest
            python -m pip install psycopg2
      - run:
          command: |  # Run test suite
            pipenv run pytest -s
            python setup.py pytest

workflows:
  build_test_publish:
    jobs:
      - build_db
      - build_test
